name: AWS Elastic Beanstalk Deployment
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-west-1"
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.PAT }}
        ref: main
    - name: Install and run deployment
      run: |
        python -m pip install --upgrade pip
        python -m spacy download en_core_web_sm
        pip install --no-cache-dir awsebcli
        nlp = spacy.load("en_core_web_sm")
        eb deploy personal-profile
        - name: Install and run deployment
    - name: Revert commit on deployment failure
      if: ${{ failure() }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git reset --hard 'HEAD~1'
        git push --force
